service: RestApi

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  region: us-east-1
  timeout: 30
 
# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  hello:
    handler: handler.hello
    events:
     - http: ANY /{proxy+}
     - http: ANY /
    environment:
     MONGO_URI: "mongodb+srv://olafgorman:pXKNq7aVJ3IMuryQ@cluster0.x98whkz.mongodb.net/rest-db"
     STRIPE_SECRET_TEST: "sk_test_51LlFJoBbpWw7toheL46xeETadDznAowlhs6YOGt9H72vXx5BBtUjDqeoviM3mzQQWWG28tac378I7462sBhZoPg600Nn4lK03R"

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
